Fixed several issues with Git's `summarize` alias.
1. The order of the commits was reversed, so the result would often
   produce no diff when one was expected (as there were no changes with
   the common ancestor).

2. Updated the alias so that it always uses a Bash shell. This required
   explicitly invoking Bash and tweaking how the command-line arguments
   are parsed.

3. Fixed the diff options being in the incorrect place for the command.

diff --git a/gitconfig b/gitconfig
--- a/gitconfig
+++ b/gitconfig
@@ -257,21 +257,18 @@
 
     # Summarize the changes (as a diff) between the current branch/commit and the branch/commit specified by the user.
     # The diff will be taken against the current HEAD.
-    summarize = "!                                                                  \
-        summarize() {                                                               \
-            if [ ${#} -lt 1 ]; then                                                 \
-                echo 'Error: Improper number of command line arguments specified' ; \
-                echo 'Usage: git summarize <commit> [diff_options]' ;               \
-                return 1 ;                                                          \
-            fi &&                                                                   \
-                                                                                    \
-            target_commit=\"${1}\" &&                                               \
-            source_commit=\"$(git rev-parse --verify HEAD)\" &&                     \
-            git diff \"${source_commit}...${target_commit}\" ;                      \
-        } &&                                                                        \
-                                                                                    \
-        summarize \"${@}\";                                                         \
-        exit ${?}"
+    summarize = "!bash -c '                                                             \
+            if [ ${#} -lt 1 ]; then                                                     \
+                echo \"Error: Improper number of command line arguments specified\" ;   \
+                echo \"Usage: git summarize <commit> [diff_options]\" ;                 \
+                exit 1 ;                                                                \
+            fi &&                                                                       \
+                                                                                        \
+            source_commit=\"${0}\" &&                                                   \
+            target_commit=\"$(git rev-parse --verify HEAD)\" &&                         \
+            git diff \"${@:1}\" \"${source_commit}...${target_commit}\" ;               \
+        '                                                                               \
+        \"${@}\""
 
     # Show the Git history is a visualized graph/tree format that displays the underlying structure of the dependencies
     # between commits. This is useful for showing merges, such as branches that have been merged into the current one.
